
pancreas_refseq_rpkms_counts_3514sc_clean.txt:
    sed -e s'/pancreas_refseq_rpkms_counts_3514sc

pancreas_refseq_rpkms_counts_3514sc_clean_v2.txt:
    sed -e s'/^[ \t]*//' pancreas_refseq_rpkms_counts_3514sc_clean.txt \
        > pancreas_refseq_rpkms_counts_3514sc_clean_v2.txt